# Uncomment the next line to define a global platform for your project
target 'covid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '13.4'

  # Pods for covid

end
